//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CARDEntities : DbContext
    {
        public CARDEntities()
            : base("name=CARDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardInfo> CardInfoes { get; set; }
    
        public virtual ObjectResult<isExistCard_Result> isExistCard(string cardNum)
        {
            var cardNumParameter = cardNum != null ?
                new ObjectParameter("CardNum", cardNum) :
                new ObjectParameter("CardNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isExistCard_Result>("isExistCard", cardNumParameter);
        }
    
        public virtual ObjectResult<CardInfo> ExistCard(string cardNum)
        {
            var cardNumParameter = cardNum != null ?
                new ObjectParameter("CardNum", cardNum) :
                new ObjectParameter("CardNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CardInfo>("ExistCard", cardNumParameter);
        }
    
        public virtual ObjectResult<CardInfo> ExistCard(string cardNum, MergeOption mergeOption)
        {
            var cardNumParameter = cardNum != null ?
                new ObjectParameter("CardNum", cardNum) :
                new ObjectParameter("CardNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CardInfo>("ExistCard", mergeOption, cardNumParameter);
        }
    }
}
